const REGISTER_IS_LOADING = 'REGISTER_IS_LOADING';
const REGISTER_HAS_ERROR = 'REGISTER_HAS_ERROR';
const REGISTER_POST_DATA_SUCCESS = 'REGISTER_POST_DATA_SUCCESS';

export default {
  REGISTER_IS_LOADING,
  REGISTER_HAS_ERROR,
  REGISTER_POST_DATA_SUCCESS
};
